### ISSUE TITLE
the browser calling server functions when there is no server yet should not crash

### ISSUE THREAD

**Issue by Pomax** [Pomax/socketless#47]
vis: "are we flying" webclient with `--browser` without the server running.

**Comment by Pomax** [comment]
```
file:///C:/Users/Mike/Documents/Git/projects/are-we-flying/node_modules/socketless/src/index.js:246
            while (steps.length) target = target[steps.shift()];
                                                ^

TypeError: Cannot read properties of undefined (reading 'authenticate')
    at UpgradedSocket.<anonymous> (file:///C:/Users/Mike/Documents/Git/projects/are-we-flying/node_modules/socketless/src/index.js:246:49)
    at UpgradedSocket.emit (node:events:524:35)
    at Receiver.receiverOnMessage (C:\Users\Mike\Documents\Git\projects\are-we-flying\node_modules\ws\lib\websocket.js:1192:20)
    at Receiver.emit (node:events:512:28)
    at Receiver.dataMessage (C:\Users\Mike\Documents\Git\projects\are-we-flying\node_modules\ws\lib\receiver.js:560:14)
    at Receiver.getData (C:\Users\Mike\Documents\Git\projects\are-we-flying\node_modules\ws\lib\receiver.js:478:17)
    at Receiver.startLoop (C:\Users\Mike\Documents\Git\projects\are-we-flying\node_modules\ws\lib\receiver.js:167:22)
    at Receiver._write (C:\Users\Mike\Documents\Git\projects\are-we-flying\node_modules\ws\lib\receiver.js:93:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)

Node.js v19.8.1
```

**Comment by Pomax** [comment]
related: add a `.connected` flag that can be used to verify that the server exists.

**Comment by Pomax** [comment]
fixed.
